### ISSUE TITLE
[bug] ormb pull return "failed to copy: unexpected EOF"

### ISSUE THREAD

**Issue by simon-cj** [kleveross/ormb#116]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
In some case, ormb pull will return error as follow:
```
bytedance@simon  ~/go/src/github.com/kleveross/ormb   update-clever-to-klever ●  ./bin/ormb pull 192.168.22.160:30022/release/onnx:v1 --plain-http
v1: Pulling from 192.168.22.160:30022/release/onnx
Error: failed to copy: unexpected EOF
Usage:
  ormb pull [flags]

Flags:
  -h, --help         help for pull
      --insecure     allow connections to TLS registry without certs (default true)
      --plain-http   use plain http and not https

Global Flags:
      --config string      config file (default is $HOME/.ormb/config.yaml)
      --log-level uint32   Log level (default 4)

PANI[2020-08-24T19:15:33+08:00] Failed to run the  command                    error="failed to copy: unexpected EOF"
panic: (*logrus.Entry) (0x17a1480,0xc00013cbd0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00013c000, 0xc0004a6ab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bytedance/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2da
github.com/sirupsen/logrus.(*Entry).Log(0xc00013caf0, 0x0, 0xc000713f08, 0x1, 0x1)
	/Users/bytedance/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logln(0xc00013caf0, 0x0, 0xc000713f58, 0x1, 0x1)
	/Users/bytedance/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:359 +0xd1
github.com/sirupsen/logrus.(*Entry).Panicln(...)
	/Users/bytedance/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:397
github.com/kleveross/ormb/cmd/ormb/cmd.Execute()
	/Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/cmd/root.go:45 +0xcb
main.main()
	/Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/main.go:23 +0x20
```

in this case, if rootPath is '$homd/.ormb', there are no error, but if rootPath is other directory, the error is 👆.

after analysis， the panic is occur in  harbor， harbor error as follow：
```
2020/08/25 06:41:30 httputil: ReverseProxy read error during body copy: unexpected EOF
2020/08/25 06:41:30.808 [C] [panic.go:679]  the request url is  /v2/release/pmml/blobs/sha256:23f00978e0c8712228ad3cae5aaae4acf0d96d8f420200838fb515333733fdc9
2020/08/25 06:41:30.808 [C] [panic.go:679]  Handler crashed with error net/http: abort Handler
2020/08/25 06:41:30.808 [C] [panic.go:679]  /usr/local/go/src/runtime/panic.go:679
2020/08/25 06:41:30.808 [C] [panic.go:679]  /usr/local/go/src/net/http/httputil/reverseproxy.go:299
2020/08/25 06:41:30.808 [C] [panic.go:679]  /harbor/src/server/middleware/v2auth/auth.go:147
2020/08/25 06:41:30.808 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.808 [C] [panic.go:679]  /harbor/src/server/middleware/artifactinfo/artifact_info.go:91
2020/08/25 06:41:30.808 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.808 [C] [panic.go:679]  /harbor/src/server/router/router.go:90
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/vendor/github.com/astaxie/beego/router.go:769
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:52
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/notification/notification.go:31
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:57
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/orm/orm.go:53
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:57
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:52
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/security/security.go:62
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:52
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/session/session.go:34
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/log/log.go:33
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:57
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/requestid/requestid.go:37
2020/08/25 06:41:30.809 [C] [panic.go:679]  /harbor/src/server/middleware/middleware.go:57
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2007
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:2802
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/net/http/server.go:1890
2020/08/25 06:41:30.809 [C] [panic.go:679]  /usr/local/go/src/runtime/asm_amd64.s:1357
```
harbor's issue at https://github.com/goharbor/harbor/issues/6527

some conclusion:

-  if harbor deploy out of k8s, there are not any error.

- if harbor deploy in k8s, and the ormbfile.yaml as follow, there are not any error.
```
author: chenjun <chenjun@caicloud.io>
format: GraphDef
framework: TensorFlow
```

- if hrabor deploy in k8s, and the ormbfile.yaml as follow, there are error like 👆.
```
author: chenjun <chenjun@caicloud.io>
format: GraphDef
framework: TensorFlow
signature:
  layers:
    - name: Placeholder
    - name: Const
    - name: Pad
    - name: Identity
    - name: Conv2D
    - name: FusedBatchNorm
    - name: Relu6
    - name: DepthwiseConv2dNative
    - name: Add
    - name: Mean
    - name: MatMul
    - name: BiasAdd
    - name: Softmax
  inputs:
    - name: input_1
      dtype: float32
      size:
      - -1
      - 224
      - 224
      - 3
  outputs:
    - name: Logits/Softmax
      dtype: float32
      size:
        - -1
        - 1000
```

@gaocegege do you have any ideas?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
The bug will present only harbor depoyed in k8s, and I delete registry pod, db pod, redis pod, and push model again, the bug is disappear.
May there have inconsistent data， because I set `--set persistence.enabled=false` when I install harbor.

**Comment by gaocegege** [comment]
Did we solve it?

**Comment by simon-cj** [comment]
Yes， not recurrence recently
