### ISSUE TITLE
Ormb login 503 error

### ISSUE THREAD

**Issue by xieydd** [kleveross/ormb#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
when i login with ormb, it will be 503 error, log is below:
```
$ ./bin/ormb login  harbor.xieydd.com -u root -p Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login insecurely
INFO[2020-10-05T17:25:20+08:00] Error logging in to v2 endpoint, trying next endpoint: Get "https://harbor.xieydd.com/v2/": EOF 
INFO[2020-10-05T17:25:22+08:00] Error logging in to v2 endpoint, trying next endpoint: login attempt to http://harbor.xieydd.com/v2/ failed with status: 503 Service Unavailable 
Error: login attempt to http://harbor.xieydd.com/v2/ failed with status: 503 Service Unavailable
Usage:
  ormb login [flags]

Flags:
  -h, --help              help for login
      --insecure          allow connections to TLS registry without certs (default true)
  -p, --password string   registry password or identity token
      --password-stdin    read password or identity token from stdin
  -u, --username string   registry username

Global Flags:
      --config string      config file (default is $HOME/.ormb/config.yaml)
      --log-level uint32   Log level (default 4)

PANI[2020-10-05T17:25:22+08:00] Failed to run the  command                    error="login attempt to http://harbor.xieydd.com/v2/ failed with status: 503 Service Unavailable"
panic: (*logrus.Entry) 0xc000459570

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000200e0, 0xc0004a9d70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
github.com/sirupsen/logrus.(*Entry).Log(0xc000459500, 0x0, 0xc00025ff08, 0x1, 0x1)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
github.com/sirupsen/logrus.(*Entry).Logln(0xc000459500, 0x0, 0xc00025ff58, 0x1, 0x1)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:359 +0xd6
github.com/sirupsen/logrus.(*Entry).Panicln(...)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:397
github.com/kleveross/ormb/cmd/ormb/cmd.Execute()
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/cmd/ormb/cmd/root.go:45 +0xd0
main.main()
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/cmd/ormb/main.go:23 +0x25
(base) 

```
**What you expected to happen**:
ormb login sucessful
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
docker login is ok
```
$ sudo docker login  harbor.xieydd.com -u xieydd -p Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/xieyuandong/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
(base) 

```

**Comment by gaocegege** [comment]
What's the version of harbor?

/cc @simon-cj

**Comment by xieydd** [comment]
I use the latest version of harbor via helm chart.

**Comment by gaocegege** [comment]
I tried to login using ormb 0.0.6 and latest harbor, it works:

```bash
ormb login --insecure 10.227.73.xx
Username: admin
Password:
Login insecurely
INFO[2020-10-09T09:45:55+08:00] Error logging in to v2 endpoint, trying next endpoint: Get "https://10.227.73.xx/v2/": dial tcp 10.227.73.xx:443: connect: connection refused
```

**Comment by simon-cj** [comment]
We are using harbor v2.1.0, you can using http(--insecure) and try again @xieydd

**Comment by xieydd** [comment]
I use nginx pod ip and https port, it works.
```
$ ./bin/ormb login  172.16.93.122:8443 -u xieydd -p Harbor12345
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login insecurely
(base) 
```

But i meet other problem :
```
$ ./bin/ormb save ./examples/PMML-model 172.16.93.122:8443/ormb/pmml:v1
ref:       172.16.93.122:8443/ormb/pmml:v1
digest:    33de07f5a506037cf451c1076938f42422726df96f682ca79ce45e18f329ae0a
size:      6.1 KiB
format:    PMML
v1: saved
(base) 
# xieyuandong @ AILab in ~/Workspace/go/src/github.com/kleveross/ormb on git:master x [22:44:49] 
$ ./bin/ormb push ./examples/PMML-model 172.16.93.122:8443/ormb/pmml:v1
Error: Model not found: ./examples/PMML-model:latest
Usage:
  ormb push [flags]

Flags:
  -h, --help         help for push
      --insecure     allow connections to TLS registry without certs (default true)
      --plain-http   use plain http and not https

Global Flags:
      --config string      config file (default is $HOME/.ormb/config.yaml)
      --log-level uint32   Log level (default 4)

PANI[2020-10-09T22:44:58+08:00] Failed to run the  command                    error="Model not found: ./examples/PMML-model:latest"
panic: (*logrus.Entry) 0xc0004ba0e0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000122000, 0xc000483590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2ea
github.com/sirupsen/logrus.(*Entry).Log(0xc0004ba070, 0x0, 0xc00026ff08, 0x1, 0x1)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:268 +0xf0
github.com/sirupsen/logrus.(*Entry).Logln(0xc0004ba070, 0x0, 0xc00026ff58, 0x1, 0x1)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:359 +0xd6
github.com/sirupsen/logrus.(*Entry).Panicln(...)
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/vendor/github.com/sirupsen/logrus/entry.go:397
github.com/kleveross/ormb/cmd/ormb/cmd.Execute()
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/cmd/ormb/cmd/root.go:45 +0xd0
main.main()
	/home/xieyuandong/Workspace/go/src/github.com/kleveross/ormb/cmd/ormb/main.go:23 +0x25

```

**Comment by gaocegege** [comment]
```diff
- ./bin/ormb push ./examples/PMML-model 172.16.93.122:8443/ormb/pmml:v1
+ ./bin/ormb push 172.16.93.122:8443/ormb/pmml:v1
```

**Comment by xieydd** [comment]
haha, my mistake.
