### ISSUE TITLE
How to push model into demo.goharbor.io from machine behind proxy

### ISSUE THREAD

**Issue by hemantha-kumara** [kleveross/ormb#168]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
I am trying out ormb commands to push models into **demo.goharbor.io**

1. Executing ormb commands from Linux VM behind a proxy
2. ormb login was failing before setting https_proxy but after setting the https_proxy, ormb login is succesfful
3. ormb push is failing with connection timeout(even after setting proxy)

**What you expected to happen**:
ormb push should be successful after setting https_proxy

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
ormb push demo.goharbor.io/ormb/xgboostsample:v1
The push refers to repository [demo.goharbor.io/ormb/xgboostsample]
ref:       demo.goharbor.io/ormb/xgboostsample:v1
digest:    b57ea86dceff41196d633005bbaeb70af71ad2a7b3e8a8f490ad06757d1436fa
size:      905 B
format:    XGBoost
Error: failed to do request: Head "https://demo.goharbor.io/v2/ormb/xgboostsample/blobs/sha256:e56034e222179843e08f702fe87e6e9804bef82aea085cc8d8620ac51487282c": dial tcp 3.138.250.43:443: connect: connection timed out
Usage:
  ormb push [flags]

Flags:
  -h, --help         help for push
      --insecure     allow connections to TLS registry without certs (default true)
      --plain-http   use plain http and not https

Global Flags:
      --config string      config file (default is $HOME/.ormb/config.yaml)
      --log-level uint32   Log level (default 4)

PANI[2021-01-05T15:21:51Z] Failed to run the  command                    error="failed to do request: Head \"https://demo.goharbor.io/v2/ormb/xgboostsample/blobs/sha256:e56034e222179843e08f702fe87e6e9804bef82aea085cc8d8620ac51487282c\": dial tcp 3.138.250.43:443: connect: connection timed out"
panic: (*logrus.Entry) (0xb9acc0,0xc0003693b0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000d8000, 0xc0003758c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2da
github.com/sirupsen/logrus.(*Entry).Log(0xc000369340, 0x0, 0xc00025ff08, 0x1, 0x1)
        /Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logln(0xc000369340, 0x0, 0xc00025ff58, 0x1, 0x1)
        /Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:359 +0xd1
github.com/sirupsen/logrus.(*Entry).Panicln(...)
        /Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:397
github.com/kleveross/ormb/cmd/ormb/cmd.Execute()
        /Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/cmd/root.go:45 +0xcb
main.main()
        /Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/main.go:23 +0x20
```

**Comment by simon-cj** [comment]
Can you show us the https_proxy config? I am not sure if it’s a proxy issue.

**Comment by hemantha-kumara** [comment]
> Can you show us the https_proxy config? I am not sure if it’s a proxy issue.

I am setting an environment variable(https_proxy)  in the shell prompt before executing ormb push
`export https_proxy=<proxyhost:proxyport>`
