### ISSUE TITLE
Push failed for Harbor v1.10.1

### ISSUE THREAD

**Issue by ESWZY** [kleveross/ormb#178]
Hello!

I followed all steps of the doc, and pushed a model to demo.harbor.io (Horbor v2.2.1). However, when I pushed it to private Harbor (v1.10.1), it said 500 Internal Server Error. 

The private Harbor has same configuration as demo.harbor.io, and also works fine for docker images.

Logs look like this:

```
[root@master tmp]# ormb models
REPOSITORY                  TAG      MODEL ID     CREATED              SIZE  
demo.goharbor.io/ormb/mnist ckpt_220 dccd443a50ed 23 minutes ago       19.1KB
10.10.102.19/ormb/mnist     ckpt_220 e9c7de20c500 17 minutes ago       19.1KB



[root@master tmp]# ormb push demo.goharbor.io/ormb/mnist:ckpt_220
The push refers to repository [demo.goharbor.io/ormb/mnist]
ref:       demo.goharbor.io/ormb/mnist:ckpt_220
digest:    dccd443a50ed86b0c6f079211dd16438c50317a5609be146bfdc03cabbc5e353
size:      19.1KB
format:    SavedModel
ckpt_220: pushed to remote (1 layer, 19.1KB total)



[root@master tmp]# ormb push 10.10.102.19/ormb/mnist:ckpt_220
The push refers to repository [10.10.102.19/ormb/mnist]
ref:       10.10.102.19/ormb/mnist:ckpt_220
digest:    e9c7de20c5004a2e61878076bd0a203a30eacb62ca23efdfabd36690c058acb4
size:      19.1KB
format:    SavedModel
Error: failed commit on ref "manifest-sha256:cad5e95d482846312cc2147a60503cd84e7052c4c33ac0d94406247d06280e05": unexpected status: 500 Internal Server Error
Usage:
  ormb push [flags]

Flags:
  -h, --help         help for push
      --insecure     allow connections to TLS registry without certs (default true)
      --plain-http   use plain http and not https

Global Flags:
      --config string      config file (default is $HOME/.ormb/config.yaml)
      --log-level uint32   Log level (default 4)

PANI[2021-05-04T20:51:39+08:00] Failed to run the  command                    error="failed commit on ref \"manifest-sha256:cad5e95d482846312cc2147a60503cd84e7052c4c33ac0d94406247d06280e05\": unexpected status: 500 Internal Server Error"
panic: (*logrus.Entry) 0xc0003f05b0

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000150000, 0xc000291c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2ea
github.com/sirupsen/logrus.(*Entry).Log(0xc0003f04d0, 0x0, 0xc000627f08, 0x1, 0x1)
	/Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xf0
github.com/sirupsen/logrus.(*Entry).Logln(0xc0003f04d0, 0x0, 0xc000627f58, 0x1, 0x1)
	/Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:359 +0xd6
github.com/sirupsen/logrus.(*Entry).Panicln(...)
	/Users/bytedance/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:397
github.com/kleveross/ormb/cmd/ormb/cmd.Execute()
	/Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/cmd/root.go:45 +0xd0
main.main()
	/Users/bytedance/go/src/github.com/kleveross/ormb/cmd/ormb/main.go:23 +0x25
```

**Comment by FogDong** [comment]
Hi ESWZY!
You can try to use `--plain-http` if your private harbor registry is under `http`.

**Comment by ESWZY** [comment]
> Hi ESWZY!
> You can try to use `--plain-http` if your private harbor registry is under `http`.

Thanks, I tried to add `--plain-http` to the end of `ormb push 10.10.102.19/ormb/mnist:ckpt_220`, but it returned 401 Unauthorized

![image](https://user-images.githubusercontent.com/32200887/117286881-4f177280-ae9c-11eb-80bf-b574080688db.png)

BTW, I have changed my private Harbor to v2..2.0, and it successed.
